#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazete.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Firindan")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdisyon(Adisyon instance);
    partial void UpdateAdisyon(Adisyon instance);
    partial void DeleteAdisyon(Adisyon instance);
    partial void InsertAdisyonBilgi(AdisyonBilgi instance);
    partial void UpdateAdisyonBilgi(AdisyonBilgi instance);
    partial void DeleteAdisyonBilgi(AdisyonBilgi instance);
    partial void InsertBorc(Borc instance);
    partial void UpdateBorc(Borc instance);
    partial void DeleteBorc(Borc instance);
    partial void InsertCariOdeme(CariOdeme instance);
    partial void UpdateCariOdeme(CariOdeme instance);
    partial void DeleteCariOdeme(CariOdeme instance);
    partial void InsertGider(Gider instance);
    partial void UpdateGider(Gider instance);
    partial void DeleteGider(Gider instance);
    partial void InsertMasa(Masa instance);
    partial void UpdateMasa(Masa instance);
    partial void DeleteMasa(Masa instance);
    partial void InsertMasaTipi(MasaTipi instance);
    partial void UpdateMasaTipi(MasaTipi instance);
    partial void DeleteMasaTipi(MasaTipi instance);
    partial void InsertMusteriOdeme(MusteriOdeme instance);
    partial void UpdateMusteriOdeme(MusteriOdeme instance);
    partial void DeleteMusteriOdeme(MusteriOdeme instance);
    partial void InsertOdemeTipi(OdemeTipi instance);
    partial void UpdateOdemeTipi(OdemeTipi instance);
    partial void DeleteOdemeTipi(OdemeTipi instance);
    partial void InsertUrun(Urun instance);
    partial void UpdateUrun(Urun instance);
    partial void DeleteUrun(Urun instance);
    partial void InsertUrunTuru(UrunTuru instance);
    partial void UpdateUrunTuru(UrunTuru instance);
    partial void DeleteUrunTuru(UrunTuru instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Gazete.Data.Properties.Settings.Default.FirindanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adisyon> Adisyon
		{
			get
			{
				return this.GetTable<Adisyon>();
			}
		}
		
		public System.Data.Linq.Table<AdisyonBilgi> AdisyonBilgi
		{
			get
			{
				return this.GetTable<AdisyonBilgi>();
			}
		}
		
		public System.Data.Linq.Table<Borc> Borc
		{
			get
			{
				return this.GetTable<Borc>();
			}
		}
		
		public System.Data.Linq.Table<CariOdeme> CariOdeme
		{
			get
			{
				return this.GetTable<CariOdeme>();
			}
		}
		
		public System.Data.Linq.Table<Gider> Gider
		{
			get
			{
				return this.GetTable<Gider>();
			}
		}
		
		public System.Data.Linq.Table<Masa> Masa
		{
			get
			{
				return this.GetTable<Masa>();
			}
		}
		
		public System.Data.Linq.Table<MasaTipi> MasaTipi
		{
			get
			{
				return this.GetTable<MasaTipi>();
			}
		}
		
		public System.Data.Linq.Table<MusteriOdeme> MusteriOdeme
		{
			get
			{
				return this.GetTable<MusteriOdeme>();
			}
		}
		
		public System.Data.Linq.Table<OdemeTipi> OdemeTipi
		{
			get
			{
				return this.GetTable<OdemeTipi>();
			}
		}
		
		public System.Data.Linq.Table<Urun> Urun
		{
			get
			{
				return this.GetTable<Urun>();
			}
		}
		
		public System.Data.Linq.Table<UrunTuru> UrunTuru
		{
			get
			{
				return this.GetTable<UrunTuru>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adisyon")]
	public partial class Adisyon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private System.Nullable<int> _MusteriKod;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<bool> _KapandiMi;
		
		private EntitySet<AdisyonBilgi> _AdisyonBilgi;
		
		private EntitySet<MusteriOdeme> _MusteriOdeme;
		
		private EntityRef<Masa> _Masa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnMusteriKodChanging(System.Nullable<int> value);
    partial void OnMusteriKodChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnKapandiMiChanging(System.Nullable<bool> value);
    partial void OnKapandiMiChanged();
    #endregion
		
		public Adisyon()
		{
			this._AdisyonBilgi = new EntitySet<AdisyonBilgi>(new Action<AdisyonBilgi>(this.attach_AdisyonBilgi), new Action<AdisyonBilgi>(this.detach_AdisyonBilgi));
			this._MusteriOdeme = new EntitySet<MusteriOdeme>(new Action<MusteriOdeme>(this.attach_MusteriOdeme), new Action<MusteriOdeme>(this.detach_MusteriOdeme));
			this._Masa = default(EntityRef<Masa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriKod", DbType="Int")]
		public System.Nullable<int> MusteriKod
		{
			get
			{
				return this._MusteriKod;
			}
			set
			{
				if ((this._MusteriKod != value))
				{
					if (this._Masa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriKodChanging(value);
					this.SendPropertyChanging();
					this._MusteriKod = value;
					this.SendPropertyChanged("MusteriKod");
					this.OnMusteriKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KapandiMi", DbType="Bit")]
		public System.Nullable<bool> KapandiMi
		{
			get
			{
				return this._KapandiMi;
			}
			set
			{
				if ((this._KapandiMi != value))
				{
					this.OnKapandiMiChanging(value);
					this.SendPropertyChanging();
					this._KapandiMi = value;
					this.SendPropertyChanged("KapandiMi");
					this.OnKapandiMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adisyon_AdisyonBilgi", Storage="_AdisyonBilgi", ThisKey="Kod", OtherKey="AdisyonKod")]
		public EntitySet<AdisyonBilgi> AdisyonBilgi
		{
			get
			{
				return this._AdisyonBilgi;
			}
			set
			{
				this._AdisyonBilgi.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adisyon_MusteriOdeme", Storage="_MusteriOdeme", ThisKey="Kod", OtherKey="AdisyonKod")]
		public EntitySet<MusteriOdeme> MusteriOdeme
		{
			get
			{
				return this._MusteriOdeme;
			}
			set
			{
				this._MusteriOdeme.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Masa_Adisyon", Storage="_Masa", ThisKey="MusteriKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public Masa Masa
		{
			get
			{
				return this._Masa.Entity;
			}
			set
			{
				Masa previousValue = this._Masa.Entity;
				if (((previousValue != value) 
							|| (this._Masa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Masa.Entity = null;
						previousValue.Adisyon.Remove(this);
					}
					this._Masa.Entity = value;
					if ((value != null))
					{
						value.Adisyon.Add(this);
						this._MusteriKod = value.Kod;
					}
					else
					{
						this._MusteriKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("Masa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdisyonBilgi(AdisyonBilgi entity)
		{
			this.SendPropertyChanging();
			entity.Adisyon = this;
		}
		
		private void detach_AdisyonBilgi(AdisyonBilgi entity)
		{
			this.SendPropertyChanging();
			entity.Adisyon = null;
		}
		
		private void attach_MusteriOdeme(MusteriOdeme entity)
		{
			this.SendPropertyChanging();
			entity.Adisyon = this;
		}
		
		private void detach_MusteriOdeme(MusteriOdeme entity)
		{
			this.SendPropertyChanging();
			entity.Adisyon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdisyonBilgi")]
	public partial class AdisyonBilgi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private System.Nullable<int> _AdisyonKod;
		
		private System.Nullable<int> _UrunKod;
		
		private System.Nullable<decimal> _UrunAdet;
		
		private EntityRef<Adisyon> _Adisyon;
		
		private EntityRef<Urun> _Urun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnAdisyonKodChanging(System.Nullable<int> value);
    partial void OnAdisyonKodChanged();
    partial void OnUrunKodChanging(System.Nullable<int> value);
    partial void OnUrunKodChanged();
    partial void OnUrunAdetChanging(System.Nullable<decimal> value);
    partial void OnUrunAdetChanged();
    #endregion
		
		public AdisyonBilgi()
		{
			this._Adisyon = default(EntityRef<Adisyon>);
			this._Urun = default(EntityRef<Urun>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdisyonKod", DbType="Int")]
		public System.Nullable<int> AdisyonKod
		{
			get
			{
				return this._AdisyonKod;
			}
			set
			{
				if ((this._AdisyonKod != value))
				{
					if (this._Adisyon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdisyonKodChanging(value);
					this.SendPropertyChanging();
					this._AdisyonKod = value;
					this.SendPropertyChanged("AdisyonKod");
					this.OnAdisyonKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKod", DbType="Int")]
		public System.Nullable<int> UrunKod
		{
			get
			{
				return this._UrunKod;
			}
			set
			{
				if ((this._UrunKod != value))
				{
					if (this._Urun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunKodChanging(value);
					this.SendPropertyChanging();
					this._UrunKod = value;
					this.SendPropertyChanged("UrunKod");
					this.OnUrunKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdet", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> UrunAdet
		{
			get
			{
				return this._UrunAdet;
			}
			set
			{
				if ((this._UrunAdet != value))
				{
					this.OnUrunAdetChanging(value);
					this.SendPropertyChanging();
					this._UrunAdet = value;
					this.SendPropertyChanged("UrunAdet");
					this.OnUrunAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adisyon_AdisyonBilgi", Storage="_Adisyon", ThisKey="AdisyonKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public Adisyon Adisyon
		{
			get
			{
				return this._Adisyon.Entity;
			}
			set
			{
				Adisyon previousValue = this._Adisyon.Entity;
				if (((previousValue != value) 
							|| (this._Adisyon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adisyon.Entity = null;
						previousValue.AdisyonBilgi.Remove(this);
					}
					this._Adisyon.Entity = value;
					if ((value != null))
					{
						value.AdisyonBilgi.Add(this);
						this._AdisyonKod = value.Kod;
					}
					else
					{
						this._AdisyonKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("Adisyon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urun_AdisyonBilgi", Storage="_Urun", ThisKey="UrunKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public Urun Urun
		{
			get
			{
				return this._Urun.Entity;
			}
			set
			{
				Urun previousValue = this._Urun.Entity;
				if (((previousValue != value) 
							|| (this._Urun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Urun.Entity = null;
						previousValue.AdisyonBilgi.Remove(this);
					}
					this._Urun.Entity = value;
					if ((value != null))
					{
						value.AdisyonBilgi.Add(this);
						this._UrunKod = value.Kod;
					}
					else
					{
						this._UrunKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("Urun");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Borc")]
	public partial class Borc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<System.DateTime> _Tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    #endregion
		
		public Borc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(100)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CariOdeme")]
	public partial class CariOdeme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<System.DateTime> _Tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    #endregion
		
		public CariOdeme()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gider")]
	public partial class Gider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<System.DateTime> _Tarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    #endregion
		
		public Gider()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(100)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Masa")]
	public partial class Masa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Ad;
		
		private System.Nullable<int> _MasaTipiKod;
		
		private System.Nullable<bool> _AcikKapali;
		
		private EntitySet<Adisyon> _Adisyon;
		
		private EntityRef<MasaTipi> _MasaTipi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnMasaTipiKodChanging(System.Nullable<int> value);
    partial void OnMasaTipiKodChanged();
    partial void OnAcikKapaliChanging(System.Nullable<bool> value);
    partial void OnAcikKapaliChanged();
    #endregion
		
		public Masa()
		{
			this._Adisyon = new EntitySet<Adisyon>(new Action<Adisyon>(this.attach_Adisyon), new Action<Adisyon>(this.detach_Adisyon));
			this._MasaTipi = default(EntityRef<MasaTipi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasaTipiKod", DbType="Int")]
		public System.Nullable<int> MasaTipiKod
		{
			get
			{
				return this._MasaTipiKod;
			}
			set
			{
				if ((this._MasaTipiKod != value))
				{
					if (this._MasaTipi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasaTipiKodChanging(value);
					this.SendPropertyChanging();
					this._MasaTipiKod = value;
					this.SendPropertyChanged("MasaTipiKod");
					this.OnMasaTipiKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcikKapali", DbType="Bit")]
		public System.Nullable<bool> AcikKapali
		{
			get
			{
				return this._AcikKapali;
			}
			set
			{
				if ((this._AcikKapali != value))
				{
					this.OnAcikKapaliChanging(value);
					this.SendPropertyChanging();
					this._AcikKapali = value;
					this.SendPropertyChanged("AcikKapali");
					this.OnAcikKapaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Masa_Adisyon", Storage="_Adisyon", ThisKey="Kod", OtherKey="MusteriKod")]
		public EntitySet<Adisyon> Adisyon
		{
			get
			{
				return this._Adisyon;
			}
			set
			{
				this._Adisyon.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MasaTipi_Masa", Storage="_MasaTipi", ThisKey="MasaTipiKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public MasaTipi MasaTipi
		{
			get
			{
				return this._MasaTipi.Entity;
			}
			set
			{
				MasaTipi previousValue = this._MasaTipi.Entity;
				if (((previousValue != value) 
							|| (this._MasaTipi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MasaTipi.Entity = null;
						previousValue.Masa.Remove(this);
					}
					this._MasaTipi.Entity = value;
					if ((value != null))
					{
						value.Masa.Add(this);
						this._MasaTipiKod = value.Kod;
					}
					else
					{
						this._MasaTipiKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("MasaTipi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Adisyon(Adisyon entity)
		{
			this.SendPropertyChanging();
			entity.Masa = this;
		}
		
		private void detach_Adisyon(Adisyon entity)
		{
			this.SendPropertyChanging();
			entity.Masa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MasaTipi")]
	public partial class MasaTipi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Tur;
		
		private EntitySet<Masa> _Masa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnTurChanging(string value);
    partial void OnTurChanged();
    #endregion
		
		public MasaTipi()
		{
			this._Masa = new EntitySet<Masa>(new Action<Masa>(this.attach_Masa), new Action<Masa>(this.detach_Masa));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tur", DbType="NVarChar(50)")]
		public string Tur
		{
			get
			{
				return this._Tur;
			}
			set
			{
				if ((this._Tur != value))
				{
					this.OnTurChanging(value);
					this.SendPropertyChanging();
					this._Tur = value;
					this.SendPropertyChanged("Tur");
					this.OnTurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MasaTipi_Masa", Storage="_Masa", ThisKey="Kod", OtherKey="MasaTipiKod")]
		public EntitySet<Masa> Masa
		{
			get
			{
				return this._Masa;
			}
			set
			{
				this._Masa.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Masa(Masa entity)
		{
			this.SendPropertyChanging();
			entity.MasaTipi = this;
		}
		
		private void detach_Masa(Masa entity)
		{
			this.SendPropertyChanging();
			entity.MasaTipi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusteriOdeme")]
	public partial class MusteriOdeme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private System.Nullable<int> _AdisyonKod;
		
		private System.Nullable<int> _OdemeTipiKod;
		
		private System.Nullable<decimal> _OdemeTutar;
		
		private EntityRef<Adisyon> _Adisyon;
		
		private EntityRef<OdemeTipi> _OdemeTipi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnAdisyonKodChanging(System.Nullable<int> value);
    partial void OnAdisyonKodChanged();
    partial void OnOdemeTipiKodChanging(System.Nullable<int> value);
    partial void OnOdemeTipiKodChanged();
    partial void OnOdemeTutarChanging(System.Nullable<decimal> value);
    partial void OnOdemeTutarChanged();
    #endregion
		
		public MusteriOdeme()
		{
			this._Adisyon = default(EntityRef<Adisyon>);
			this._OdemeTipi = default(EntityRef<OdemeTipi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdisyonKod", DbType="Int")]
		public System.Nullable<int> AdisyonKod
		{
			get
			{
				return this._AdisyonKod;
			}
			set
			{
				if ((this._AdisyonKod != value))
				{
					if (this._Adisyon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdisyonKodChanging(value);
					this.SendPropertyChanging();
					this._AdisyonKod = value;
					this.SendPropertyChanged("AdisyonKod");
					this.OnAdisyonKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTipiKod", DbType="Int")]
		public System.Nullable<int> OdemeTipiKod
		{
			get
			{
				return this._OdemeTipiKod;
			}
			set
			{
				if ((this._OdemeTipiKod != value))
				{
					if (this._OdemeTipi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOdemeTipiKodChanging(value);
					this.SendPropertyChanging();
					this._OdemeTipiKod = value;
					this.SendPropertyChanged("OdemeTipiKod");
					this.OnOdemeTipiKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTutar", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> OdemeTutar
		{
			get
			{
				return this._OdemeTutar;
			}
			set
			{
				if ((this._OdemeTutar != value))
				{
					this.OnOdemeTutarChanging(value);
					this.SendPropertyChanging();
					this._OdemeTutar = value;
					this.SendPropertyChanged("OdemeTutar");
					this.OnOdemeTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adisyon_MusteriOdeme", Storage="_Adisyon", ThisKey="AdisyonKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public Adisyon Adisyon
		{
			get
			{
				return this._Adisyon.Entity;
			}
			set
			{
				Adisyon previousValue = this._Adisyon.Entity;
				if (((previousValue != value) 
							|| (this._Adisyon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adisyon.Entity = null;
						previousValue.MusteriOdeme.Remove(this);
					}
					this._Adisyon.Entity = value;
					if ((value != null))
					{
						value.MusteriOdeme.Add(this);
						this._AdisyonKod = value.Kod;
					}
					else
					{
						this._AdisyonKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("Adisyon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OdemeTipi_MusteriOdeme", Storage="_OdemeTipi", ThisKey="OdemeTipiKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public OdemeTipi OdemeTipi
		{
			get
			{
				return this._OdemeTipi.Entity;
			}
			set
			{
				OdemeTipi previousValue = this._OdemeTipi.Entity;
				if (((previousValue != value) 
							|| (this._OdemeTipi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OdemeTipi.Entity = null;
						previousValue.MusteriOdeme.Remove(this);
					}
					this._OdemeTipi.Entity = value;
					if ((value != null))
					{
						value.MusteriOdeme.Add(this);
						this._OdemeTipiKod = value.Kod;
					}
					else
					{
						this._OdemeTipiKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("OdemeTipi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OdemeTipi")]
	public partial class OdemeTipi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Tip;
		
		private EntitySet<MusteriOdeme> _MusteriOdeme;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnTipChanging(string value);
    partial void OnTipChanged();
    #endregion
		
		public OdemeTipi()
		{
			this._MusteriOdeme = new EntitySet<MusteriOdeme>(new Action<MusteriOdeme>(this.attach_MusteriOdeme), new Action<MusteriOdeme>(this.detach_MusteriOdeme));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip", DbType="NVarChar(50)")]
		public string Tip
		{
			get
			{
				return this._Tip;
			}
			set
			{
				if ((this._Tip != value))
				{
					this.OnTipChanging(value);
					this.SendPropertyChanging();
					this._Tip = value;
					this.SendPropertyChanged("Tip");
					this.OnTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OdemeTipi_MusteriOdeme", Storage="_MusteriOdeme", ThisKey="Kod", OtherKey="OdemeTipiKod")]
		public EntitySet<MusteriOdeme> MusteriOdeme
		{
			get
			{
				return this._MusteriOdeme;
			}
			set
			{
				this._MusteriOdeme.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MusteriOdeme(MusteriOdeme entity)
		{
			this.SendPropertyChanging();
			entity.OdemeTipi = this;
		}
		
		private void detach_MusteriOdeme(MusteriOdeme entity)
		{
			this.SendPropertyChanging();
			entity.OdemeTipi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urun")]
	public partial class Urun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Ad;
		
		private System.Nullable<decimal> _Fiyat;
		
		private System.Nullable<decimal> _Adet;
		
		private System.Nullable<int> _UrunTuruKod;
		
		private EntitySet<AdisyonBilgi> _AdisyonBilgi;
		
		private EntityRef<UrunTuru> _UrunTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    partial void OnAdetChanging(System.Nullable<decimal> value);
    partial void OnAdetChanged();
    partial void OnUrunTuruKodChanging(System.Nullable<int> value);
    partial void OnUrunTuruKodChanged();
    #endregion
		
		public Urun()
		{
			this._AdisyonBilgi = new EntitySet<AdisyonBilgi>(new Action<AdisyonBilgi>(this.attach_AdisyonBilgi), new Action<AdisyonBilgi>(this.detach_AdisyonBilgi));
			this._UrunTuru = default(EntityRef<UrunTuru>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruKod", DbType="Int")]
		public System.Nullable<int> UrunTuruKod
		{
			get
			{
				return this._UrunTuruKod;
			}
			set
			{
				if ((this._UrunTuruKod != value))
				{
					if (this._UrunTuru.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunTuruKodChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruKod = value;
					this.SendPropertyChanged("UrunTuruKod");
					this.OnUrunTuruKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urun_AdisyonBilgi", Storage="_AdisyonBilgi", ThisKey="Kod", OtherKey="UrunKod")]
		public EntitySet<AdisyonBilgi> AdisyonBilgi
		{
			get
			{
				return this._AdisyonBilgi;
			}
			set
			{
				this._AdisyonBilgi.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UrunTuru_Urun", Storage="_UrunTuru", ThisKey="UrunTuruKod", OtherKey="Kod", IsForeignKey=true, DeleteRule="CASCADE")]
		public UrunTuru UrunTuru
		{
			get
			{
				return this._UrunTuru.Entity;
			}
			set
			{
				UrunTuru previousValue = this._UrunTuru.Entity;
				if (((previousValue != value) 
							|| (this._UrunTuru.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UrunTuru.Entity = null;
						previousValue.Urun.Remove(this);
					}
					this._UrunTuru.Entity = value;
					if ((value != null))
					{
						value.Urun.Add(this);
						this._UrunTuruKod = value.Kod;
					}
					else
					{
						this._UrunTuruKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("UrunTuru");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdisyonBilgi(AdisyonBilgi entity)
		{
			this.SendPropertyChanging();
			entity.Urun = this;
		}
		
		private void detach_AdisyonBilgi(AdisyonBilgi entity)
		{
			this.SendPropertyChanging();
			entity.Urun = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UrunTuru")]
	public partial class UrunTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kod;
		
		private string _Tur;
		
		private EntitySet<Urun> _Urun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKodChanging(int value);
    partial void OnKodChanged();
    partial void OnTurChanging(string value);
    partial void OnTurChanged();
    #endregion
		
		public UrunTuru()
		{
			this._Urun = new EntitySet<Urun>(new Action<Urun>(this.attach_Urun), new Action<Urun>(this.detach_Urun));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tur", DbType="NVarChar(50)")]
		public string Tur
		{
			get
			{
				return this._Tur;
			}
			set
			{
				if ((this._Tur != value))
				{
					this.OnTurChanging(value);
					this.SendPropertyChanging();
					this._Tur = value;
					this.SendPropertyChanged("Tur");
					this.OnTurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UrunTuru_Urun", Storage="_Urun", ThisKey="Kod", OtherKey="UrunTuruKod")]
		public EntitySet<Urun> Urun
		{
			get
			{
				return this._Urun;
			}
			set
			{
				this._Urun.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Urun(Urun entity)
		{
			this.SendPropertyChanging();
			entity.UrunTuru = this;
		}
		
		private void detach_Urun(Urun entity)
		{
			this.SendPropertyChanging();
			entity.UrunTuru = null;
		}
	}
}
#pragma warning restore 1591
